apps/main/urls.py
from django.urls import path
from .views import exam, auth, account, attempt

app_name = "customer"

urlpatterns = [
    # auth urls...
    path("auth/login/", auth.login_view, name="login"),
    path("auth/register/", auth.register_view, name="register"),
    path("auth/logout/", auth.logout_view, name="logout"),

    # account urls...
    path('account/me/', account.account_view, name="account"),
    path('account/settings/', account.settings_view, name="settings"),

    # customer urls...
    path("", exam.customer_dashboard_view, name="dashboard"),
    path("exams/", exam.customer_exams_view, name="exams"),
    path("exams/<int:exam_id>/", exam.customer_exam_detail_view, name="exam_detail"),
    path("exams/<int:exam_id>/start/", exam.customer_exam_start_view, name="exam_start"),

    # attempt urls...
    path("attempts/<int:attempt_id>/", attempt.attempt_detail_view, name="attempt_detail"),
    path("attempts/<int:attempt_id>/question/", attempt.attempt_question_view, name="attempt_question"),

    # HTMX save (question_id URL-да!)
    path("attempts/<int:attempt_id>/q/<int:question_id>/answer/", attempt.attempt_answer_view, name="attempt_answer"),

    path("attempts/<int:attempt_id>/q/<int:question_id>/speaking/", attempt.attempt_speaking_upload_view,
         name="attempt_speaking_upload"),
    path("attempts/<int:attempt_id>/q/<int:question_id>/writing/", attempt.attempt_writing_submit_view,
         name="attempt_writing_submit"),
    path("attempts/<int:attempt_id>/submit/", attempt.attempt_submit_view, name="attempt_submit"),
    path("attempts/<int:attempt_id>/review/", attempt.attempt_review_view, name="attempt_review"),
]

apps/manager/urls.py
from django.urls import path

app_name = "main"

urlpatterns = [

]

config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve


urlpatterns = [
    path("admin/", admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    path("", include("apps.main.urls")),
    path("manager/", include("apps.manager.urls")),

]


urlpatterns += [re_path(r"^i18n/", include("django.conf.urls.i18n"))]
urlpatterns += [re_path(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT})]
urlpatterns += [re_path(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT})]

if settings.DEBUG:
    urlpatterns += [path("__reload__/", include("django_browser_reload.urls"))]

ui/templates/layouts/account_layout.html
{% extends 'layouts/base_layout.html' %}
{% load static %}

{% block base_layout %}
<div class="grid md:flex items-start gap-8 py-6 px-4">
    <ul class="max-w-64 w-full hidden md:grid gap-1">
        <li>
            <a href="{% url 'customer:account' %}" class="py-2 px-4 w-full block hover:bg-primary-100 rounded-xl {% if request.path == '/account/me/' %}bg-primary-600 hover:bg-primary-800 text-white{% endif %}">
                Аккаунт
            </a>
        </li>
        <li>
            <a href="{% url 'customer:settings' %}" class="py-2 px-4 w-full block hover:bg-primary-100 rounded-xl {% if request.path == '/account/settings/' %}bg-primary-600 hover:bg-primary-800 text-white{% endif %}">
                Баптаулар
            </a>
        </li>
    </ul>

    <ul class="flex md:hidden w-full font-medium text-center">
        <li class="whitespace-nowrap">
            <a href="{% url 'customer:account' %}" class="p-2 border-b-4 {% if request.path == '/account/me/' %}border-b-4 border-primary-600{% else %}border-transparent{% endif %}">
                Аккаунт
            </a>
        </li>
        <li>
            <a href="{% url 'customer:settings' %}" class="p-2 border-b-4 {% if request.path == '/account/settings/' %}border-b-4 border-primary-600{% else %}border-transparent{% endif %}">
                Баптаулар
            </a>
        </li>
    </ul>

    <div class="flex-1">
        {% block account_layout %}
        {% endblock account_layout %}
    </div>
</div>
{% endblock base_layout %}

ui/templates/layouts/auth_layout.html
{% extends 'base.html' %}
{% load static %}


{% block base %}
<div class="min-h-screen flex justify-center items-center">
    <div class="max-w-md space-y-4 w-full p-4">
        <div class="flex justify-center">
            <img src="{% static 'images/full-logo.svg' %}" alt="TestApp Logo" class="h-12 w-auto">
        </div>

        <div class="relative">
            {% block auth_layout %}
            {% endblock auth_layout %}
        </div>
    </div>
</div>
{% endblock base %}

ui/templates/layouts/base_layout.html
{% extends 'base.html' %}
{% load static %}


{% block base %}
<nav class="fixed top-0 z-50 w-full bg-white border-b border-secondary-200">
    <div class="px-3 py-3 lg:px-5 lg:pl-3">
        <div class="flex items-center justify-between">
            <div class="flex items-center justify-start rtl:justify-end">
                <button 
                    data-drawer-target="logo-sidebar" 
                    data-drawer-toggle="logo-sidebar" 
                    aria-controls="logo-sidebar"
                    type="button"
                    class="inline-flex items-center p-2 text-muted rounded-lg sm:hidden hover:bg-secondary-100 focus:outline-none focus:ring-2 focus:ring-secondary-200"
                >
                    <span class="sr-only">Open sidebar</span>
                    <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20"
                        xmlns="http://www.w3.org/2000/svg">
                        <path clip-rule="evenodd" fill-rule="evenodd"
                            d="M2 4.75A.75.75 0 012.75 4h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 4.75zm0 10.5a.75.75 0 01.75-.75h7.5a.75.75 0 010 1.5h-7.5a.75.75 0 01-.75-.75zM2 10a.75.75 0 01.75-.75h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 10z">
                        </path>
                    </svg>
                </button>
                <a href="{% url 'customer:dashboard' %}" class="flex ms-2 md:me-24">
                    <img src="{% static 'images/full-logo.svg' %}" class="w-32" alt="CSgrade Logo" />
                </a>
            </div>
            <div class="flex items-center">
                <div class="flex items-center ms-3">
                    <div>
                        <button type="button"
                            class="flex rounded-full focus:ring-4 focus:ring-secondary-300"
                            aria-expanded="false" data-dropdown-toggle="dropdown-user"
                        >
                            <span class="sr-only">Open user menu</span>
                            {% if user.avatar %}
                                <img 
                                    class="w-8 h-8 rounded-full"
                                    src="{{ user.avatar.url }}" alt="user photo"
                                >
                            {% else %}
                                <div 
                                    class="w-8 h-8 rounded-full bg-secondary-100 flex items-center justify-center text-foreground"
                                >
                                    {{ user.first_name|first|upper }}{{ user.last_name|first|upper }}
                                </div>
                            {% endif %}
                        </button>
                    </div>
                    <div 
                        class="z-50 hidden my-4 list-none bg-white divide-y divide-secondary-100 shadow-sm rounded-xl"
                        id="dropdown-user"
                    >
                        <div class="px-4 py-3" role="none">
                            <h1 class="font-semibold text-base" role="none">
                                {{ user.first_name }} {{ user.last_name }}
                            </h1>
                            <p class="font-medium truncate text-blue-600 mb-1" role="none">
                                {{ user.email }}
                            </p>
                        </div>
                        <ul class="py-1" role="none">
                            <li>
                                <a href="{% url 'customer:account' %}"
                                    class="block px-4 py-2 font-medium hover:bg-secondary-100"
                                    role="menuitem">Аккаунт</a>
                            </li>
                            <li>
                                <a href="{% url 'customer:settings' %}"
                                    class="block px-4 py-2 font-medium hover:bg-secondary-100"
                                    role="menuitem">Баптаулар</a>
                            </li>
                            <li>
                                <form action="{% url 'customer:logout' %}" method="post">
                                    {% csrf_token %}
                                    <button type="submit" class="w-full cursor-pointer text-left block px-4 py-2 font-medium hover:bg-secondary-100">Шығу</button>
                                </form>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</nav>

<aside 
    id="logo-sidebar"
    class="fixed top-0 left-0 z-40 w-64 h-screen pt-20 transition-transform -translate-x-full bg-white border-r border-secondary-200 sm:translate-x-0"
    aria-label="Sidebar"
>
    <div class="h-full px-3 pb-4 overflow-y-auto bg-white">
        <ul class="space-y-2 font-medium">
            <li>
                <a 
                    href="{% url 'customer:dashboard' %}"
                    class="
                        flex items-center py-2 px-4 rounded-xl group 
                        {% if request.path == '/' %}bg-primary-600 text-white hover:bg-primary-600{% else %}hover:bg-secondary-100{% endif %}
                    "
                >
                    <svg class="w-5 h-5 transition duration-75 {% if request.path == '/' %}group-hover:text-white{% else %}group-hover:text-primary-600{% endif %}"
                        aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 21">
                        <path
                            d="M16.975 11H10V4.025a1 1 0 0 0-1.066-.998 8.5 8.5 0 1 0 9.039 9.039.999.999 0 0 0-1-1.066h.002Z" />
                        <path
                            d="M12.5 0c-.157 0-.311.01-.565.027A1 1 0 0 0 11 1.02V10h8.975a1 1 0 0 0 1-.935c.013-.188.028-.374.028-.565A8.51 8.51 0 0 0 12.5 0Z" />
                    </svg>
                    <span class="ms-3">Басты бет</span>
                </a>
            </li>
            <li>
                <a 
                    href="{% url 'customer:exams' %}"
                    class="
                        flex items-center py-2 px-4 rounded-xl group 
                        {% if request.path == '/exams/' %}bg-primary-600 text-white hover:bg-primary-600{% else %}hover:bg-secondary-100{% endif %}    
                    "
                >
                    <svg class="shrink-0 w-5 h-5 transition duration-75 {% if request.path == '/exams/' %}group-hover:text-white{% else %}group-hover:text-primary-600{% endif %}"
                        aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 18 18">
                        <path
                            d="M6.143 0H1.857A1.857 1.857 0 0 0 0 1.857v4.286C0 7.169.831 8 1.857 8h4.286A1.857 1.857 0 0 0 8 6.143V1.857A1.857 1.857 0 0 0 6.143 0Zm10 0h-4.286A1.857 1.857 0 0 0 10 1.857v4.286C10 7.169 10.831 8 11.857 8h4.286A1.857 1.857 0 0 0 18 6.143V1.857A1.857 1.857 0 0 0 16.143 0Zm-10 10H1.857A1.857 1.857 0 0 0 0 11.857v4.286C0 17.169.831 18 1.857 18h4.286A1.857 1.857 0 0 0 8 16.143v-4.286A1.857 1.857 0 0 0 6.143 10Zm10 0h-4.286A1.857 1.857 0 0 0 10 11.857v4.286c0 1.026.831 1.857 1.857 1.857h4.286A1.857 1.857 0 0 0 18 16.143v-4.286A1.857 1.857 0 0 0 16.143 10Z" />
                    </svg>
                    <span class="flex-1 ms-3 whitespace-nowrap">Тестілеулер</span>
                </a>
            </li>
        </ul>
    </div>
</aside>

<div class="p-4 sm:ml-64 mt-14">
    {% block base_layout %}
    {% endblock base_layout %}
</div>
{% endblock base %}

ui/templates/layouts/customer_layout.html
{% extends 'base.html' %}
{% load static %}


{% block base %}
<nav class="fixed top-0 z-50 w-full bg-white border-b border-gray-200">
    <div class="px-3 py-3 lg:px-5 lg:pl-3">
        <div class="flex items-center justify-between">
            <div class="flex items-center justify-start rtl:justify-end">
                <button data-drawer-target="logo-sidebar" data-drawer-toggle="logo-sidebar" aria-controls="logo-sidebar"
                    type="button"
                    class="inline-flex items-center p-2 text-sm text-gray-500 rounded-lg sm:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600">
                    <span class="sr-only">Open sidebar</span>
                    <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20"
                        xmlns="http://www.w3.org/2000/svg">
                        <path clip-rule="evenodd" fill-rule="evenodd"
                            d="M2 4.75A.75.75 0 012.75 4h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 4.75zm0 10.5a.75.75 0 01.75-.75h7.5a.75.75 0 010 1.5h-7.5a.75.75 0 01-.75-.75zM2 10a.75.75 0 01.75-.75h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 10z">
                        </path>
                    </svg>
                </button>
                <a href="{% url 'customer:dashboard' %}" class="flex ms-2 md:me-24">
                    <img src="{% static 'images/full-logo.svg' %}" class="w-32" alt="TestApp Logo" />
                </a>
            </div>
            <div class="flex items-center">
                <div class="flex items-center ms-3">
                    <div>
                        <button type="button"
                            class="flex text-sm bg-gray-800 rounded-full focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600"
                            aria-expanded="false" data-dropdown-toggle="dropdown-user"
                        >
                            <span class="sr-only">Open user menu</span>
                            {% if user.avatar %}
                                <img 
                                    class="w-8 h-8 rounded-full"
                                    src="{{ user.avatar.url }}" alt="user photo"
                                >
                            {% else %}
                                <div 
                                    class="w-8 h-8 rounded-full bg-secondary-100 flex items-center justify-center text-foreground"
                                >
                                    {{ user.first_name|first|upper }}{{ user.last_name|first|upper }}
                                </div>
                            {% endif %}
                        </button>
                    </div>
                    <div class="z-50 hidden my-4 text-base list-none bg-white divide-y divide-gray-100 rounded-sm shadow-sm dark:bg-gray-700 dark:divide-gray-600"
                        id="dropdown-user">
                        <div class="px-4 py-3" role="none">
                            <p class="text-sm text-gray-900 dark:text-white" role="none">
                                {{ user.first_name }} {{ user.last_name }}
                            </p>
                            <p class="text-sm font-medium text-gray-900 truncate dark:text-gray-300" role="none">
                                {{ user.email }}
                            </p>
                        </div>
                        <ul class="py-1" role="none">
                            <li>
                                <form 
                                    action="{% url 'main:logout' %}" 
                                    method="post" 
                                    class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-600 dark:hover:text-white" role="menuitem"
                                >
                                    {% csrf_token %}
                                    <button type="submit" class="w-full text-left">Жүйеден шығу</button>
                                </form>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</nav>

<aside id="logo-sidebar"
    class="fixed top-0 left-0 z-40 w-64 h-screen pt-20 transition-transform -translate-x-full bg-white border-r border-gray-200 sm:translate-x-0 dark:bg-gray-800 dark:border-gray-700"
    aria-label="Sidebar">
    <div class="h-full px-3 pb-4 overflow-y-auto bg-white dark:bg-gray-800">
        <ul class="space-y-2 font-medium">
            <li>
                <a href="{% url 'customer:dashboard' %}"
                    class="flex items-center p-2 text-gray-900 rounded-lg group">
                    <svg class="w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white"
                        aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 21">
                        <path
                            d="M16.975 11H10V4.025a1 1 0 0 0-1.066-.998 8.5 8.5 0 1 0 9.039 9.039.999.999 0 0 0-1-1.066h.002Z" />
                        <path
                            d="M12.5 0c-.157 0-.311.01-.565.027A1 1 0 0 0 11 1.02V10h8.975a1 1 0 0 0 1-.935c.013-.188.028-.374.028-.565A8.51 8.51 0 0 0 12.5 0Z" />
                    </svg>
                    <span class="ms-3">Басты бет</span>
                </a>
            </li>
            <li>
                <a href="#"
                    class="flex items-center p-2 text-gray-900 rounded-lg group">
                    <svg class="shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white"
                        aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 18 18">
                        <path
                            d="M6.143 0H1.857A1.857 1.857 0 0 0 0 1.857v4.286C0 7.169.831 8 1.857 8h4.286A1.857 1.857 0 0 0 8 6.143V1.857A1.857 1.857 0 0 0 6.143 0Zm10 0h-4.286A1.857 1.857 0 0 0 10 1.857v4.286C10 7.169 10.831 8 11.857 8h4.286A1.857 1.857 0 0 0 18 6.143V1.857A1.857 1.857 0 0 0 16.143 0Zm-10 10H1.857A1.857 1.857 0 0 0 0 11.857v4.286C0 17.169.831 18 1.857 18h4.286A1.857 1.857 0 0 0 8 16.143v-4.286A1.857 1.857 0 0 0 6.143 10Zm10 0h-4.286A1.857 1.857 0 0 0 10 11.857v4.286c0 1.026.831 1.857 1.857 1.857h4.286A1.857 1.857 0 0 0 18 16.143v-4.286A1.857 1.857 0 0 0 16.143 10Z" />
                    </svg>
                    <span class="flex-1 ms-3 whitespace-nowrap">Барлық тесттер</span>
                </a>
            </li>
        </ul>
    </div>
</aside>

<div class="p-4 sm:ml-64 mt-14">
    {% block customer_layout %}
    {% endblock customer_layout %}
</div>
{% endblock base %}